# Generated by Django 3.2.7 on 2021-10-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_alter_movie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('TR', 'Thriller'), ('RO', 'Romantic'), ('AC', 'Action'), ('HO', 'Horror'), ('CR', 'Crime')], default='AC', max_length=2),
        ),
    ]
