# Generated by Django 3.2.7 on 2021-10-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0006_auto_20211007_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='photo',
            field=models.ImageField(null=True, upload_to='movie_imgs'),
        ),
    ]
